# Generated by Django 4.1 on 2022-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=264)),
                ("lastname", models.CharField(max_length=264)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
